# Generated by Django 3.0.5 on 2020-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAddress',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
