version: '3.7'

services:
  island:
    image: missingno/island
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - mysql
    environment:
      ENV_FILE: /run/secrets/dj_envs
    secrets:
      - dj_envs
    entrypoint: "./migrations-entrypoint.sh"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: island
      MYSQL_ROOT_PASSWORD: island

secrets:
  dj_envs:
    # See example.env
    file: test.env
