version: '3.7'

services:
  island:
    image: missingno/island
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      - mysql
      - rabbitmq
    env_file:
      # See example.env
      - test.env
    entrypoint: "./migrations-entrypoint.sh"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: island
      MYSQL_ROOT_PASSWORD: island

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: island
      RABBITMQ_DEFAULT_PASS: island
      RABBITMQ_DEFAULT_VHOST: island
    restart: always
    expose:
      - "5672"
