version: '3.7'

services:
  island:
    image: missingno/island
    volumes:
      - ./log:/app/log
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      # See example.env
      - test.env
#    networks:
#      - rabbitmq

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    restart: always
    environment:
      MYSQL_DATABASE: island
      MYSQL_ROOT_PASSWORD: island
#    networks:
#      - rabbitmq

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./redis:/data
    expose:
      - "6379"
#    networks:
#      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-alpine
    environment:
      RABBITMQ_DEFAULT_USER: island
      RABBITMQ_DEFAULT_PASS: island
      RABBITMQ_DEFAULT_VHOST: island
# It may not work in Windows environment due to permission issues, just comment the "volumes" section.
#    volumes:
#      - ./rabbitmq:/var/lib/rabbitmq
    restart: always
    expose:
      - "5672"

#networks:
#  rabbitmq:
#    name: crawlers_default
#    external: true
