# Generated by Django 3.0.5 on 2020-05-09 03:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TweetData',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('new', models.BooleanField(default=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_image.Task')),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField(unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='twitter_image.TweetData')),
            ],
        ),
    ]
